### ISSUE TITLE
Error when trying to download weights

### ISSUE THREAD

**Issue by paucarre** [YouHuang67/focsam#2]
When trying to click on the link of the following line in the `README.md`: 

Download: Obtain the pretrained [FocSAM-ViT-H](https://drive.google.com/file/d/1VOeMkY9LovfWYi66JMR8q79gFiC4n3Az/view?usp=sharing), and unzip it in work_dirs/focsam/focsam_vit_huge_eval.

I get the following on my browser:
![Screenshot from 2024-05-27 23-58-54](https://github.com/YouHuang67/focsam/assets/17511850/5a2da175-64f7-4b98-bda4-d1a5abae4182)

The other link from this line of the `README.md` works perfectly well:
Download: Acquire the pretrained [SAM-ViT-H](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth) and save it to pretrain/sam_vit_h_4b8939.pth.

No error on this one, it can be downloaded.

**Comment by YouHuang67** [comment]
Apologies for the inconvenience. The Google Drive link has been updated, and you should be able to download it now.
